openapi: 3.1.0
info:
  title: Nitro Server Routes
servers:
  - url: https://ziit.app
    description: Local Development Server
    variables: {}
paths:
  /api/external/heartbeats:
    post:
      tags:
        - API Routes
      parameters: []
      responses:
        '200':
          description: OK
      description: Submit coding activity heartbeat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - timestamp
                - project
                - language
                - editor
                - os
              properties:
                timestamp:
                  type: string
                  format: date-time
                project:
                  type: string
                language:
                  type: string
                editor:
                  type: string
                os:
                  type: string
                branch:
                  type: string
                file:
                  type: string
  /api/external/batch:
    post:
      tags:
        - API Routes
      parameters: []
      responses:
        '200':
          description: OK
      description: Submit multiple coding activity heartbeats in batch
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                required:
                  - timestamp
                  - project
                  - language
                  - editor
                  - os
                properties:
                  timestamp:
                    type: string
                    format: date-time
                  project:
                    type: string
                  language:
                    type: string
                  editor:
                    type: string
                  os:
                    type: string
                  branch:
                    type: string
                  file:
                    type: string
  /api/external/stats:
    get:
      tags:
        - API Routes
      parameters:
        - in: query
          name: timeRange
          required: true
          schema:
            type: string
            enum:
              - today
              - yesterday
              - week
              - month
              - month_to_date
              - last_month
              - year_to_date
              - last_12_months
              - all_time
        - in: query
          name: midnightOffsetSeconds
          required: false
          schema:
            type: integer
          description: Offset in seconds from midnight for day boundaries
      responses:
        '200':
          description: OK
      description: Get user statistics via API key
  /api/external/user:
    get:
      tags:
        - API Routes
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
                  githubId:
                    type: string
                  githubUsername:
                    type: string
                  apiKey:
                    type: string
                  keystrokeTimeout:
                    type: integer
      description: Get user information via API key