// This file is auto-generated by scripts/generate-icon-map.mjs
// Do not edit this file directly.

import type { FunctionComponent, SVGProps } from 'react';

import MdiDocker from '~icons/mdi/docker';
import MdiGithub from '~icons/mdi/github';

export const mdiIcons: Record<string, FunctionComponent<SVGProps<SVGSVGElement>>> = {
  Docker: MdiDocker,
  Github: MdiGithub,
};
